version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: glameo_beauty_backend
      POSTGRES_PASSWORD: glameo_beauty_backend
      POSTGRES_DB: glameo_beauty_backend
    ports:
      - "5433:5432"
    networks:
      - glameo-network

  backend:
    build: .
    container_name: glameo-backend
    depends_on:
      - db
    environment:
      DATABASE_NAME: glameo_beauty_backend
      DATABASE_USER: glameo_beauty_backend
      DATABASE_PASSWORD: glameo_beauty_backend
      DATABASE_HOST: db     
      DATABASE_PORT: 5432
    ports:
      - "8080:8000"
    networks:
      - glameo-network

networks:
  glameo-network:
    driver: bridge
